/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/domainAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/inputClassifier`; params?: Router.UnknownInputParams; } | { pathname: `/services/linkAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/phoneAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/pixAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/webSearch`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/services/domainAnalyzer`; params?: Router.UnknownOutputParams; } | { pathname: `/services/inputClassifier`; params?: Router.UnknownOutputParams; } | { pathname: `/services/linkAnalyzer`; params?: Router.UnknownOutputParams; } | { pathname: `/services/phoneAnalyzer`; params?: Router.UnknownOutputParams; } | { pathname: `/services/pixAnalyzer`; params?: Router.UnknownOutputParams; } | { pathname: `/services/webSearch`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/services/domainAnalyzer${`?${string}` | `#${string}` | ''}` | `/services/inputClassifier${`?${string}` | `#${string}` | ''}` | `/services/linkAnalyzer${`?${string}` | `#${string}` | ''}` | `/services/phoneAnalyzer${`?${string}` | `#${string}` | ''}` | `/services/pixAnalyzer${`?${string}` | `#${string}` | ''}` | `/services/webSearch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/domainAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/inputClassifier`; params?: Router.UnknownInputParams; } | { pathname: `/services/linkAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/phoneAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/pixAnalyzer`; params?: Router.UnknownInputParams; } | { pathname: `/services/webSearch`; params?: Router.UnknownInputParams; };
    }
  }
}
